@ACCESS_TOKEN=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiMjgzYmM5ODIxYzE3YzBlMjFlZWZkNGE2ZmU4ZTMzMDFlYzI1ZTY1OTRiYWJhZjYyNjU3NGU2MGNlOTVmM2E5YjViZDg0NTQyNjgwOGUwNTUiLCJpYXQiOjE2MDk3ODUzNzEsIm5iZiI6MTYwOTc4NTM3MSwiZXhwIjoxNjQxMzIxMzcxLCJzdWIiOiIxMSIsInNjb3BlcyI6W119.Cjud4RKqW2XGNNwNxRaXo9SkEHOO1DRjJxB_m6CPksAmfxEgiESmHKjEO3RgN6uIWLn_Bhlzld1AgjGCYIl1WgrHT2WBV52RpSX4hdu4Jeid92TxFKGCmMkrWyF465HgRLoUSaAdzWFVdgEqckIcuxKnztCVOwa1Jq12lwYj1BngCH3H_6AxNXosALoNA7UQ1Dw2Hu5TgyT_YVUl2SW9pDK9xNZqBT-RUEaCwdiBOgrXCDXAusrzkM9m-Qxw1wAdOq_3hGB1cI2b9z5TwClj_cmDtDIx3uDVzLtgNMDf6mayhmnvfxBuyJl6HTQVHa-8ixi03q39Ej2gHQXpKNBPQfKEjJiGcq5CdnKQgbWjMfBRWjFIanY6GYmagH6H2834FYbUN_uK9uK0pPWrysOVF5TC9eGAagsA1-ktciusrsLAZI2zXGONTIMLgMk7s5pdEnVt2CPZc7cMMyTGg93S6oxx85kHvcxVUfBeYyIp3dUujZdqa0iGRGpVf1dnS2eXt3bzzjSmCDEFqtlypof00-GTSUOi2OsT0Gjhv_8EFFBalpR7ETC981t3swWrbimdOamjnF3Y2cybY7ShxZa898VDIQYWJW5kGF7Mp0IV23y2G3N9soby8O6ScPy1q1I-KkJGr9hfWhSiwFplEF7H3tb1IicZKJfmBma0UZYgsZc
@REFRESH_TOKEN="refresh token"



### Home Page ###
GET http://localhost:8000/
content-type: application/json,













### Home Page ###
GET http://localhost:8000/ping
content-type: application/json,














### User Registration Submit ###
POST  http://localhost:8000/api/register
content-type: application/json

{
    "firstname":"Hari Narayan",
    "lastname":"Das",
    "email":"hndas2020@gmail.com",
    "password":"abcd"

}










### User Login Submit ###
POST  http://localhost:8000/api/login
content-type: application/json

{    
    "email":"abc2@gmail.com",
    "password":"password"
}








### User's Dashboard
GET http://localhost:8000/api/user
content-type: application/json
authorization: {{ACCESS_TOKEN}}



### All Members
GET http://localhost:8000/api/members
content-type: application/json
authorization: {{ACCESS_TOKEN}}












### Registered User's OTP Verification
POST http://localhost:8000/api/users/OTP_vefiry
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{
    "otp":"2412" 
}





### Registered User's OTP Resend
GET http://localhost:8000/api/users/OTP_resend
content-type: application/json
authorization: {{ACCESS_TOKEN}}














### User's New Post
POST http://localhost:8000/api/users/post
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{       
    "caption":"this is my caption",
    "img_link":"https://pixcel.com"
}



### User's New Comment on any post
POST http://localhost:8000/api/users/post/comment
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{    
    "post_id":"5fa2e9bf52d4601444c6e1dd",
    "comment_text":"this is my comment on any post"    
}






### User's Logout
POST http://localhost:8000/api/logout
content-type: application/json,
authorization: {{ACCESS_TOKEN}} 

{
    "refresh_token": ""
}







### New Request ###
GET http://localhost:8000/unknown






### All Clubs
GET http://localhost:8000/api/clubs




### All Clubs
POST http://localhost:8000/api/clubs/register
content-type: application/json

{

}