@ACCESS_TOKEN=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNTYwMjY0OGNiMDIyZTM2ZjIwNDA4YThiZjI4YmM1N2RkNTk3OTQzZDEwZDY3ZDY0MjQ2MjVkZDI4MmQzY2FmOThiOWFiNjQ1MDYzMjdhOWIiLCJpYXQiOjE2MTQzOTY2NTUsIm5iZiI6MTYxNDM5NjY1NSwiZXhwIjoxNjQ1OTMyNjU0LCJzdWIiOiIxMSIsInNjb3BlcyI6W119.NELADCg-rtmrN51UxsL22RjuaW7YFHHoYt_6CwOFR7A8UYzLcBfqsWpFf-uajezUxEvX8fVjc_80oK6AO3NCq9GawuBlu9bmRFYRw9e3HpFa6Slft0ZNMLyoCRu2BucL7qUztzIjzyfYBJeZtAMi-sjvad8lYrafA6SO8vC3iM5C1_PTM4DKCwff5bqsCDrIykIkGD_xHNziW5ZgzwfKZVvEbfD0XMyZ-el2ikGofNCRxErqHldoiMKKlq1I5t1txv4roM7qKWpZ9q3r_YEp_fwCdhSDke4uuX7tnhdEo3X41SgD8ormbj3Ndg5JOgjcVynK947rJiB1sw7Vydg6Pt7GVyJWEZeG6toyrei76Akxn6gPXKe3I1O0mHjuGjAo3eSfXio7GjUy1S9JWw-dxSIVYcM_WGwmoEkqnIl_xSlpw0QHeHevCAR2iMmbJDNTJywzELSWv86v5pOgaEd9ZztcMDD_kgTGYFMEOt2S9ydzIbmDYvNPVt__O26QWwpUhOvhMAS-pJ6gE4qz-hRuIKfpijQGOKMaCZYyP4zLgs-iIeucGo5sgprqMYcjCAyNlz4ZKjwzBB8RE1r00lq7wn5nrrlEpVuZ0KiKtmrpYfPrJti7oL4bM7mAckpHkQRBVg2wC-pNlpcqffIVmJ7ylYtP1MmJUlHlTHNKwNyaVQ0
@REFRESH_TOKEN="refresh token"



### Home Page ###
GET http://localhost:8000/
content-type: application/json,













### Home Page ###
GET http://localhost:8000/ping
content-type: application/json,



### All Users without auth ###
GET http://localhost:8000/api/allusers
content-type: application/json,










### User's Dashboard
GET http://localhost:8000/api/link_membership/5531
content-type: application/json
authorization: {{ACCESS_TOKEN}}







  













### User Registration Submit ###
POST  http://localhost:8000/api/register
content-type: application/json

{
    "name":"Hari Narayan Das",    
    "email":"hndas2020@gmail.com",
    "password":"password",
    "password_confirmation":"password"
}













### User Login Submit ###
POST  http://localhost:8000/api/login
content-type: application/json

{    
    "email":"abc2@gmail.com",
    "password":"password"
}








### User's Dashboard
GET http://localhost:8000/api/user
content-type: application/json
authorization: {{ACCESS_TOKEN}}



### All Members
GET http://localhost:8000/api/member/3
content-type: application/json
authorization: {{ACCESS_TOKEN}}



### Individual Members
GET http://localhost:8000/api/members/16
content-type: application/json
authorization: {{ACCESS_TOKEN}}


### Individual Members Premium Initialization
GET http://localhost:8000/api/members/16/loanpayments
content-type: application/json
authorization: {{ACCESS_TOKEN}}


### Individual Members Premium Payment
POST http://localhost:8000/api/members/16/loanpayments
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{
    "member_id":16,    
    "loanassign_id":111, 
    "loanpayment_id": 200,
    "premium_amt":1000,
    "loanpayment_date":"2021-02-25",
    "remarks":"No remarks"
}


### Individual Members Premium Initialization
PUT http://localhost:8000/api/members/16/loanpayments
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{
    "member_id":16,  
}


### Individual Members Premium Initialization
DELETE http://localhost:8000/api/members/16/loanpayments
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{
    "member_id":16,    
    "loanassign_id":52, 
    "loanpayment_id": 195,
    "premium_amt":6000,
    "loanpayment_date":"2021-01-25",
    "remarks":"No remarks",
}





### Individual Members Th Fund Initialization
GET http://localhost:8000/api/members/16/thfundmonthcollection
content-type: application/json
authorization: {{ACCESS_TOKEN}}







































### Registered User's OTP Verification
POST http://localhost:8000/api/users/OTP_vefiry
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{
    "otp":"2412" 
}





### Registered User's OTP Resend
GET http://localhost:8000/api/users/OTP_resend
content-type: application/json
authorization: {{ACCESS_TOKEN}}














### User's New Post
POST http://localhost:8000/api/users/post
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{       
    "caption":"this is my caption",
    "img_link":"https://pixcel.com"
}



### User's New Comment on any post
POST http://localhost:8000/api/users/post/comment
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{    
    "post_id":"5fa2e9bf52d4601444c6e1dd",
    "comment_text":"this is my comment on any post"    
}






### User's Logout
POST http://localhost:8000/api/logout
content-type: application/json,
authorization: {{ACCESS_TOKEN}} 

{
    "refresh_token": ""
}







### New Request ###
GET http://localhost:8000/unknown






### All Clubs
GET http://localhost:8000/api/clubs




### All Clubs
POST http://localhost:8000/api/clubs/register
content-type: application/json

{

}