@ACCESS_TOKEN=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiYjZmYzUyMzEzN2FkNzhmNzVkNzg2OTAyMDE5ODY0NzVjMWY1MDQ3NDVlNjc5ZGMxMGNlMWU5MDI0NDhkZDRmMjExODcwNTYxZDdhMTQzMDgiLCJpYXQiOjE2MTQyMjE1OTEsIm5iZiI6MTYxNDIyMTU5MSwiZXhwIjoxNjQ1NzU3NTg5LCJzdWIiOiIxMCIsInNjb3BlcyI6W119.Kvvmf2iWqBkaOS7EWhCSjmrm3Ud3MCFNXOA9OJQ4_FoLcH4tmCp7V8C3kj3I5Cyokjj1O1Pw8BuKfdwGk7zr8wOxGImoYdvncqteRe5wnOj8XVjakbribxhgDaoxPmahxkSg4tB4-K_ZyuJw9eHPyYdybdqB8hTvShuoUBhORV6jzS7UVfVok3E7SE9k_oUBlvFeGkzBIwrXMyTPut-eFUrvF3tHxjkYfs1M34J-Yaz1qcISJfmpTuEL49Qfn9pgAokxG0EsEJ_RkGub3gTkIgpmAD0IRRlRoUTtUNKs2A6N1P78qq97DP3-tQYhAgFpgFU11zOh0IWp8A4lvbXcxEBwTdDRH1FKutylaouM9SgrPoZmUSUG8LyXLKXdQNOcEx5RqxyhgN3UH0mI_04rf7iNMyoxxwcnOlI7PsbHaT9YixYuzhdmy6u5RUcqZE_dgf7jPRRNXQqwej1eOkJFVy4vbeeeMplva5vwNXLO46pJnzdxOqY7V4Ly8AHreLVa-VJfaBMOacIMRpfFnEeInRm85rek6iZI8VCKjufQ9c18Rq51yt3TsRCU9J2qumTAbnoUPoJYB-7WEQFcVYDZ_qfrNN9TiW-AeV_L3RY90HPvtO-q9G-N4rI-27FMwylz5Y8pryv4s8VX9EIs64p84-W_NcO7ZwRtYZeXFtLoiM4
@REFRESH_TOKEN="refresh token"



### Home Page ###
GET http://localhost:8000/
content-type: application/json,













### Home Page ###
GET http://localhost:8000/ping
content-type: application/json,



### All Users without auth ###
GET http://localhost:8000/api/allusers
content-type: application/json,










### User's Dashboard
GET http://localhost:8000/api/link_membership/5019
content-type: application/json
authorization: {{ACCESS_TOKEN}}





















### User Registration Submit ###
POST  http://localhost:8000/api/register
content-type: application/json

{
    "name":"Hari Narayan Das",    
    "email":"hndas2020@gmail.com",
    "password":"password",
    "password_confirmation":"password"
}













### User Login Submit ###
POST  http://localhost:8000/api/login
content-type: application/json

{    
    "email":"abc1@gmail.com",
    "password":"password"
}








### User's Dashboard
GET http://localhost:8000/api/user
content-type: application/json
authorization: {{ACCESS_TOKEN}}



### All Members
GET http://localhost:8000/api/members
content-type: application/json
authorization: {{ACCESS_TOKEN}}



### Individual Members
GET http://localhost:8000/api/members/16
content-type: application/json
authorization: {{ACCESS_TOKEN}}


### Individual Members Premium Initialization
GET http://localhost:8000/api/members/16/loanpayments
content-type: application/json
authorization: {{ACCESS_TOKEN}}


### Individual Members Premium Payment
POST http://localhost:8000/api/members/16/loanpayments
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{
    "member_id":16,    
    "loanassign_id":111, 
    "loanpayment_id": 200,
    "premium_amt":1000,
    "loanpayment_date":"2021-02-25",
    "remarks":"No remarks"
}


### Individual Members Premium Initialization
PUT http://localhost:8000/api/members/16/loanpayments
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{
    "member_id":16,  
}


### Individual Members Premium Initialization
DELETE http://localhost:8000/api/members/16/loanpayments
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{
    "member_id":16,    
    "loanassign_id":52, 
    "loanpayment_id": 195,
    "premium_amt":6000,
    "loanpayment_date":"2021-01-25",
    "remarks":"No remarks",
}




















### Registered User's OTP Verification
POST http://localhost:8000/api/users/OTP_vefiry
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{
    "otp":"2412" 
}





### Registered User's OTP Resend
GET http://localhost:8000/api/users/OTP_resend
content-type: application/json
authorization: {{ACCESS_TOKEN}}














### User's New Post
POST http://localhost:8000/api/users/post
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{       
    "caption":"this is my caption",
    "img_link":"https://pixcel.com"
}



### User's New Comment on any post
POST http://localhost:8000/api/users/post/comment
content-type: application/json
authorization: {{ACCESS_TOKEN}}

{    
    "post_id":"5fa2e9bf52d4601444c6e1dd",
    "comment_text":"this is my comment on any post"    
}






### User's Logout
POST http://localhost:8000/api/logout
content-type: application/json,
authorization: {{ACCESS_TOKEN}} 

{
    "refresh_token": ""
}







### New Request ###
GET http://localhost:8000/unknown






### All Clubs
GET http://localhost:8000/api/clubs




### All Clubs
POST http://localhost:8000/api/clubs/register
content-type: application/json

{

}